# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e50307531da103f601f86087ec6d4d0e6cae41a0469c33c716ce5e675ae58866ba7d708e43665fae01b1f9efe18fa5aa1866d03080925ee8f31d0edf81a073

test:
  secret_key_base: f69de8061f283f6b1f984f40a3e727b7445c4d04bdad5044c3e284622282d9c6ecac093c3cd2b263c30152268a5d986ff572766fde2b4ec2dcd812be6aef95ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
